# Generated by Django 5.2 on 2025-05-04 21:11

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('tracker_id', models.UUIDField(help_text='UUID primary key', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Herd',
            fields=[
                ('tracker_id', models.UUIDField(help_text='UUID primary key', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name', max_length=100)),
                ('species', models.CharField(choices=[('antelope', 'Antelope'), ('elk', 'Elk'), ('deer', 'Deer'), ('moose', 'Moose')], help_text='Species', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('tracker_id', models.UUIDField(help_text='UUID primary key', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name', max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Lat/long location', srid=4326)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('birth', 'birth'), ('death', 'death'), ('depart', 'departing members'), ('join', 'joining members')], help_text='notable event', max_length=10)),
                ('description', models.TextField(help_text='event description')),
                ('family', models.ForeignKey(help_text='Related family', on_delete=django.db.models.deletion.CASCADE, to='tracker.family')),
            ],
            options={
                'abstract': False,
                'required_db_features': ['gis_enabled'],
            },
        ),
        migrations.AddField(
            model_name='family',
            name='herd',
            field=models.ForeignKey(help_text='Related herd', on_delete=django.db.models.deletion.CASCADE, to='tracker.herd'),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('tracker_id', models.UUIDField(help_text='UUID primary key', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Friendly name', max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Lat/long location', srid=4326)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('size', models.PositiveSmallIntegerField(help_text='Count of family members')),
                ('health_rating', models.PositiveSmallIntegerField(help_text='Health rating (1-10)')),
                ('family', models.ForeignKey(help_text='Related family', on_delete=django.db.models.deletion.CASCADE, to='tracker.family')),
            ],
            options={
                'abstract': False,
                'required_db_features': ['gis_enabled'],
            },
        ),
    ]
