# Generated by Django 5.2 on 2025-05-06 12:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='size',
            new_name='family_size',
        ),
        migrations.AddField(
            model_name='observation',
            name='description',
            field=models.TextField(default=1, help_text='event description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='observation',
            name='event_type',
            field=models.CharField(choices=[('birth', 'birth'), ('death', 'death'), ('depart', 'departing members'), ('join', 'joining members'), ('obsv', 'observation')], help_text='notable event', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='herd',
            field=models.ForeignKey(help_text='Related herd', on_delete=django.db.models.deletion.CASCADE, related_name='families', to='tracker.herd'),
        ),
        migrations.AlterField(
            model_name='family',
            name='tracker_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='UUID primary key', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='herd',
            name='tracker_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='UUID primary key', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='observation',
            name='tracker_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='UUID primary key', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
