# Generated by Django 5.2 on 2025-05-06 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_size_observation_family_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='name',
        ),
    ]
